version: '3'
networks:
  flask:
  proxy:
    external: true
services:
  flask:
    image: webapp-flask
    build:
      context: ../../.
      dockerfile: Dockerfile
    depends_on:
      - data
    networks:
      - flask
    environment:
      - FLASK_ENV=staging
  web:
    image: nginx:alpine
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 5000:80
    labels:
      - traefik.enable=true
      - traefik.backend=web
      - traefik.docker.network=proxy
      - traefik.frontend.rule=Host:flask.dasilvacampos.fr
      - traefik.port=80
    networks:
      - proxy
      - flask
    depends_on:
      - flask
  data:
    image: postgres:alpine
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    networks:
      - flask
    environment:
      - POSTGRES_PASSWORD=fbapp
      - POSTGRES_USER=fbapp
      - POSTGRES_DB=fbapp

