version: '3'

services:
  flask:
    image: webapp-flask
    build:
      context: ../../.
      dockerfile: Dockerfile
    depends_on:
      - data
    environment:
      - FLASK_ENV=staging
  web:
    image: nginx:alpine
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - 5000:80
    depends_on:
      - flask
  data:
    image: postgres:alpine
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    environment:
      - POSTGRES_PASSWORD=fbapp
      - POSTGRES_USER=fbapp
      - POSTGRES_DB=fbapp


